#!/usr/bin/env python
import os
import sys

env = SConscript("../godot-cpp/SConstruct")

# Add source files
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

# Build shared library
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/example_plugin.{}.{}.framework/example_plugin.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/example_plugin{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
